package coreLG;

public class CONFIG
{
    public static String ROOT_LOCAL_URL;
    public static String ROOT_LOCAL_URL_2;
    public static String ROOT_LOCAL_WEB_URL;
    public static String ROOT_SERVER_MATTROI_URL_TEST;
    public static String ROOT_CLOUD_URL;
    public static String EDITOR_DATA_BASE;
    public static String DATA_BASE;
    public static String USERS;
    public static String PLAYER_DATA;
    public static String DATETIME_OBJECT;
    public static String INFO_OBJECT;
    public static String INVENTORY_OBJECT;
    public static String INVENTORY_GOLD;
    public static String INVENTORY_ENERGY;
    public static String PROGRESS_OBJECT;
    public static String TROPHY_OBJECT;
    public static String MONSTER_DATA;
    public static String ISLAND_DATA;
    public static String MESSAGE_TOKEN_INFO;
    public static String POST_GOLD;
    public static String POST_ONLINE;
    public static String GET_BOT_CONFIG;
    public static String POST_ROOM;
    public static String POST_REWARD;
    public static String GET_NEWUSER;
    public static String POST_GETSERVERTIME;
    public static String Web_Link;
    public static String Dynamiclink_Domain;
    public static String Android_BundleID;
    public static String IOS_IBI;
    public static String DYNAMIC_LINK;
    public static String IOSPlatformClientId;
    public static String AndroidPlatformClientId;
    public static String GET_INFO_FACEBOOK;
    public static String FB_GAME_URL;
    public static String STORE_ANDROID_URL;
    public static String STORE_IOS_URL;
    public static String[] ACCOUNT;
    public static String[] PASS;
    public static String[] VERSION;
    public static String[] SERVER;
    public static int[] PORT;
    public static String PATH_GUI;
    public static String PATH_MAP;
    public static String PATH_ITEM;
    public static String PATH_PLAYER;
    public static String PATH_EFFECT;
    public static String PATH_FONT;
    public static String PATH_GUI_RESOURCE;
    public static String PATH_MAP_RESOURCE;
    public static String PATH_ITEM_RESOURCE;
    public static String PATH_EFFECT_RESOURCE;
    
    static {
        CONFIG.ROOT_LOCAL_URL = "LOCAL:192.168.1.88:19149";
        CONFIG.ROOT_LOCAL_URL_2 = "LOCAL:192.168.1.88:19150";
        CONFIG.ROOT_LOCAL_WEB_URL = "LOCAL:192.168.1.88:19146";
        CONFIG.ROOT_SERVER_MATTROI_URL_TEST = "Mặt Trời:27.0.12.164:19149";
        CONFIG.ROOT_CLOUD_URL = "";
        CONFIG.EDITOR_DATA_BASE = "";
        CONFIG.DATA_BASE = "";
        CONFIG.USERS = "users";
        CONFIG.PLAYER_DATA = "data";
        CONFIG.DATETIME_OBJECT = "data/dateTimeData";
        CONFIG.INFO_OBJECT = "data/info";
        CONFIG.INVENTORY_OBJECT = "data/inventory";
        CONFIG.INVENTORY_GOLD = "data/inventory/gold";
        CONFIG.INVENTORY_ENERGY = "data/inventory/energy";
        CONFIG.PROGRESS_OBJECT = "data/progress";
        CONFIG.TROPHY_OBJECT = "data/progress/trophy";
        CONFIG.MONSTER_DATA = "data/playerMonsterData";
        CONFIG.ISLAND_DATA = "data/playerIslandData";
        CONFIG.MESSAGE_TOKEN_INFO = "data/info/messageToken";
        CONFIG.POST_GOLD = "PostGold";
        CONFIG.POST_ONLINE = "PostOnline";
        CONFIG.GET_BOT_CONFIG = "GetBotConFig";
        CONFIG.POST_ROOM = "PostRoom";
        CONFIG.POST_REWARD = "PostReward";
        CONFIG.GET_NEWUSER = "GetConfigNewUser";
        CONFIG.POST_GETSERVERTIME = "GetServerTime";
        CONFIG.Web_Link = "";
        CONFIG.Dynamiclink_Domain = "";
        CONFIG.Android_BundleID = "";
        CONFIG.IOS_IBI = "";
        CONFIG.DYNAMIC_LINK = "";
        CONFIG.IOSPlatformClientId = "";
        CONFIG.AndroidPlatformClientId = "";
        CONFIG.GET_INFO_FACEBOOK = "/me?fields=id,name,picture.type(square).width(128).height(128).fields(url)";
        CONFIG.FB_GAME_URL = "";
        CONFIG.STORE_ANDROID_URL = "";
        CONFIG.STORE_IOS_URL = "";
        CONFIG.ACCOUNT = new String[] { "rrwwrr", "arisol", "1ptw11" };
        CONFIG.PASS = new String[] { "aabbzz", "ngpkj", "abcd" };
        CONFIG.VERSION = new String[] { "239", "239", "239" };
        CONFIG.SERVER = new String[] { "Sv1:27.0.14.66:19150" };
        CONFIG.PORT = new int[] { 1950 };
        CONFIG.PATH_GUI = "gui/";
        CONFIG.PATH_MAP = "map/";
        CONFIG.PATH_ITEM = "item/";
        CONFIG.PATH_PLAYER = "player/";
        CONFIG.PATH_EFFECT = "effect/";
        CONFIG.PATH_FONT = "font/";
        CONFIG.PATH_GUI_RESOURCE = "UI/Old/gui/";
        CONFIG.PATH_MAP_RESOURCE = "UI/Old/map/bgItem/";
        CONFIG.PATH_ITEM_RESOURCE = "UI/Old/item/";
        CONFIG.PATH_EFFECT_RESOURCE = "UI/Old/effect/";
    }
}